---
title: "Administrative boundaries of Belgium based on OpenStreetMap data"
author: "Jan Wijffels"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{BelgiumBoundaries}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

An Introduction to **BelgiumMaps.Admin** package
=======================================


```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.extra='style="display:block; margin: auto"', fig.align="center")
```

Introduction
------------

The  **BelgiumMaps.Admin** package contains maps of Belgium extracted from OpenStreetMap


Visualization
----------------------------
This package contains administrative boundaries at different levels in the BE_OSM_ADMIN dataset.

```{r basic plots}
library(sp)
library(BelgiumMaps.Admin)
data(BE_OSM_ADMIN)
plot(BE_OSM_ADMIN)
plot(subset(BE_OSM_ADMIN, admin.level %in% "2"), main = "National")
plot(subset(BE_OSM_ADMIN, admin.level %in% "4"), main = "Regions")
plot(subset(BE_OSM_ADMIN, admin.level %in% "6"), main = "Provinces")
plot(subset(BE_OSM_ADMIN, admin.level %in% "7"), main = "Districts")
plot(subset(BE_OSM_ADMIN, admin.level %in% "8"), main = "Municipalities")
## Boundaries at the level 9 seem to be incomplete
plot(subset(BE_OSM_ADMIN, admin.level %in% "9"), main = "NISsections")
```


Integrate with BelgiumStatistics
----------------------------
The data also contains NIS codes which can be used to link against the data in the BelgiumStatistics package. This package can be found at https://github.com/jwijffels/BelgiumStatistics

```{r integrated with belgiumstatistics, eval=FALSE}
library(BelgiumStatistics)
library(BelgiumMaps.Admin)
library(data.table)
library(leaflet)

data(BE_OSM_ADMIN, package = "BelgiumMaps.Admin")
data(TF_SOC_POP_STRUCT_2015, package = "BelgiumStatistics")

x <- as.data.table(TF_SOC_POP_STRUCT_2015)
x <- x[, list(MS_POPULATION = sum(MS_POPULATION),
              Females = 100 * sum(MS_POPULATION[CD_SEX == "F"]) / sum(MS_POPULATION)),
       by = list(CD_MUNTY_REFNIS, TX_MUNTY_DESCR_NL, TX_MUNTY_DESCR_FR)]

mymap <- subset(BE_OSM_ADMIN, !is.na(tag.ref.ins))
myenrichedmap <- merge(mymap, x, by.x = "tag.ref.ins", by.y = "CD_MUNTY_REFNIS", all.x=TRUE, all.y=FALSE)
myenrichedmap <- subset(myenrichedmap, !is.na(Females))
pal <- colorNumeric(palette = "Blues", domain = myenrichedmap$Females)
leaflet(myenrichedmap) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.85, color = ~pal(Females)) %>%
  addPopups(lng = 4.366354, lat = 50.86619, popup="BNOSAC offices<br/>www.bnosac.be")
```
